# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - dev
      - ciam-master
      - release/*
  batch: True

variables:
  - name: BuildParameters.jdkVersion
    value: 1.8
  - name: BuildParameters.jdkArchitecture
    value: x64
  - name: BuildParameters.javaHomeSelection
    value: JDKVersion
  - name: robolectricSdkVersion
    value: 28

jobs:
  - job: build_test
    displayName: Build & Test
    cancelTimeoutInMinutes: 1
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - task: JavaToolInstaller@0
        displayName: Use Java 8
        inputs:
          jdkArchitectureOption: x64
          jdkSourceOption: PreInstalled
      - task: Gradle@2
        name: Gradle1
        displayName: Assemble Release
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: clean ktlintCheck clean common:assembleLocal common4j:assemble
          publishJUnitResults: false
          testResultsFiles: '**/build/test-results/TEST-*.xml'
          jdkVersion: $(BuildParameters.jdkVersion)
          jdkArchitecture: $(BuildParameters.jdkArchitecture)
          sqGradlePluginVersion: 2.0.1
      - task: Gradle@2
        displayName: Run Unit tests
        inputs:
          tasks: common:testLocalDebugUnitTest -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}} --tests *com.microsoft.identity.common.internal.providers.microsoft.nativeauth*
          javaHomeSelection: $(BuildParameters.javaHomeSelection)
          jdkVersion: 1.11
      - task: Gradle@2
        displayName: Run Unit tests in common4j
        inputs:
          tasks: common4j:test -Psugar=true -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}} --tests *com.microsoft.identity.common.java.providers.nativeauth*
          javaHomeSelection: $(BuildParameters.javaHomeSelection)
          jdkVersion: 1.11

