# File: azure-pipelines\templates\steps\spotbugs.yml
# Description: Tasks to run Spotbugs (Assemble task must run first)
# https://github.com/AzureAD/android-complete/blob/master/plugins/buildsystem/docs/Spotbugs.md

parameters:
- name: project
- name: spotbugsCommand
  default: spotbugsLocalDebug
- name: artifactName
  default: CodeAnalysisLogs
- name: cwd
  default: $(Build.SourcesDirectory)

steps:
- task: Gradle@3
  displayName: 'Run Spotbugs'
  inputs:
    jdkArchitecture: x86
    cwd: ${{ parameters.cwd }}
    tasks: ${{ parameters.project }}:${{ parameters.spotbugsCommand }}
    publishJUnitResults: false
- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: SpotBugs'
  inputs:
    targetPath: '$(Build.SourcesDirectory)\${{ parameters.project }}\build\reports\'
    ArtifactName: ${{ parameters.artifactName }}
  condition: failed()
