# File: azure-pipelines/continuous-delivery/common-cd.yml
# Description: Assemble & publish latest keyvault, labapi, labapiutilities, testutil release to internal vsts feed
# Variable: 'ENV_VSTS_MVN_ANDROIDCOMMON_USERNAME' was defined in the Variables tab
# Variable: 'customVersion' overrides the version number of the published libraries

name: 0.0.$(Date:yyyyMMdd)$(Rev:.r) # $(Build.BuildNumber) = name

trigger:
- dev
pr: none

variables:
  ${{ if eq(variables.customVersion, '') }}:
    versionNumber: $(Build.BuildNumber)
  ${{ else }}:
    versionNumber: ${{ variables.customVersion }}

pool:
  name: Hosted Windows 2019 with VS2019
jobs:
# Key Vault
- job: keyvault_phase
  displayName: 'Key Vault: Build, Test and Publish'
  steps:
  - template: ../templates/steps/continuous-delivery/assemble-publish-projversion.yml
    parameters:
      project: keyvault
      buildArguments: '-PprojVersion=$(versionNumber)'
      artifactFolder: 'keyvault/build/libs'
# Lab API
- job: labapi_phase
  displayName: 'Lab API: Build, Test and Publish'
  steps:
  - template: ../templates/steps/continuous-delivery/assemble-publish-projversion.yml
    parameters:
      project: labapi
      buildArguments: '-PprojVersion=$(versionNumber)'
      artifactFolder: 'labapi/build/libs'
# Lab API Utilities
- job: labapiutilities_phase
  displayName: 'Lab API Utilities: Build, Test and Publish'
  dependsOn:
  - keyvault_phase
  - labapi_phase
  variables:
    - group: AndroidAuthClientAutomationSecrets
    - group: MSIDLABVARS
  steps:
  - template: ../templates/steps/automation-cert.yml
    parameters:
      envVstsMvnAt: ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN
  - template: ../templates/steps/continuous-delivery/assemble-publish-projversion.yml
    parameters:
      project: LabApiUtilities
      buildArguments: '-PprojVersion=$(versionNumber)'
      artifactFolder: 'LabApiUtilities/build/libs'
      testArguments: -PlabSecret=$(LabVaultAppCert)
# Test utils
- job: testutils_phase
  displayName: 'Test utils: Build, Test and Publish'
  dependsOn:
  - keyvault_phase
  - labapi_phase
  steps:
  - template: ../templates/steps/continuous-delivery/assemble-publish-projversion.yml
    parameters:
      project: testutils
      buildArguments: '-PprojVersion=$(versionNumber)'
      artifactFolder: 'testutils/build/outputs'
# UI Automation utilities
- job: uiautomationutilities_phase
  displayName: 'UI Automation utilities: Build, Test and Publish'
  dependsOn:
  - testutils_phase
  steps:
  - template: ../templates/steps/continuous-delivery/assemble-publish-projversion.yml
    parameters:
      project: uiautomationutilities
      buildArguments: '-PprojVersion=$(versionNumber)'
      artifactFolder: 'uiautomationutilities/build/outputs'
...
